---
kind: pipeline
name: default

steps:
  - name: docker-deploy
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - ./scripts/docker-build.sh
      - ./scripts/docker-deploy.sh

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
