apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncronium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncronium
  template:
    metadata:
      labels:
        app: syncronium
    spec:
      containers:
        - image: ksidelta/syncronium:{{ required ".Values.imageTag is required" .Values.imageTag }}
          name: syncronium
          env:
            - name: MEETUP_GROUP_NAME
              value: "hspomorze"
            - name: DISCORD_GROUP_ID
              value: {{ required ".Values.discordGroup is required" .Values.discordGroup | quote }}
          envFrom:
            - secretRef:
                name: syncronium-secret
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: syncronium-data
