name: ci

on:
  push:
    branches:
      - "master"

env:
  DOCKER_USER: psuwala
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: ksidelta

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - uses: actions/checkout@v3
      - run: ./scripts/docker-build.sh
      - run: ./scripts/docker-deploy.sh
      - run: ./scripts/helm-deploy.sh
